name: Deploy ASPX App

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: windowsserver2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to IIS using Web Deploy
      shell: cmd
      run: |
        "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" ^
        -verb:sync ^
        -source:contentPath="C:\inetpub\wwwroot\aspx" ^
        -dest:auto,computerName="https://127.0.0.1:8172/msdeploy.axd?site=aspx",username='CONS',password='Cons.1234',authType='Basic' ^
        -allowUntrusted
